apiVersion: v1
kind: Service
metadata:
  name: nginx-service-clusterip
  labels:
    name: NginxServiceClusterIP
    type: front-end
spec:
  type: ClusterIP
  ports:
    - port: 80        # Port that exposed for communication.
      targetPort: 80  # Port that is avaialbe on the Kubernetes Pod.
  selector:           # Labels from the Pod definion.
    name: Nginx
    type: front-end
      