apiVersion: v1
kind: Service
metadata:
  name: nginx-service-nodeport
  labels:
    name: NginxServiceNodePort
    type: front-end
spec:
  type: NodePort
  ports:
    - nodePort: 3008  # Valid Range 30000 - 32767.
      port: 80        # Port that is created on the Service to connect with Kubernetes Pod.
      targetPort: 80  # Port that is avaialbe on the Kubernetes Pod.
  selector:           # Labels from the Pod definion.
    name: Nginx
    type: front-end
      