apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-replication-controller
  labels:
    name: NginxReplica
    type: front-end
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        name: Nginx
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3
