apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    name: NginxDeployment
    type: front-end
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        name: Nginx
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3
  selector:
    matchLabels:
      name: Nginx
      type: front-end
